# Generated by Django 5.2 on 2025-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_guests',
            field=models.IntegerField(default=1, help_text='Total guests amount'),
        ),
    ]
