# Generated by Django 5.2 on 2025-04-16 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_total_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='closing_hour',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='cafe',
            name='opening_hour',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
