# Generated by Django 5.2 on 2025-04-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_cafe_closing_hour_cafe_opening_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='closing_hour',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='opening_hour',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('visitor', 'table', 'date')},
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_guests',
        ),
    ]
